test:
	go test -v ./internal/...
test-c:
	go test -v -cover ./internal/...
test-a:
	go test -v ./...
test-ac:
	go test -v -cover ./...
test-p:
	go test -v ./problems/...
test-pc:
	go test -v -cover ./problems/...
vet:
	go vet ./...